name: Cache CI

on:
  push:
  workflow_dispatch:

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/demo
          key: cache-2ceba4b

      - name: prime-cache-2ceba4b
        run: |
          if [ "${{ steps.cache-step.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit"
          else
            echo "Cache miss â€” priming cache"
            mkdir -p ~/.cache/demo
            echo "Primed on $(date)" > ~/.cache/demo/data.txt
          fi

      - name: Show cached files
        run: ls -R ~/.cache/demo || true
